# Generated by Django 2.2.20 on 2021-07-06 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_hello'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hello',
            new_name='NewHello',
        ),
    ]
