# Generated by Django 2.2.20 on 2021-07-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210706_1614'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewHello',
            new_name='Hello',
        ),
    ]
